// api.js — thin wrappers around the Go backend methods exposed via Wails bindings.
//
// At build time Wails generates JS bindings under "wailsjs/go/main/App".
// During development (wails dev) these are auto-generated and hot-reloaded.

import {
  Register,
  Login,
  GetDeviceFingerprint,
  ListRooms,
  GetRoom,
  JoinRoom,
  LeaveRoom,
  GetMembers,
  GetBuyInfo,
  ConnectVPN,
  DisconnectVPN,
  StopVPN,
  GetVPNStatus,
  PingServer,
  GetPingStats,
  GetConnectionQuality,
  CheckVPNReady,
  IsSplitTunnelActive,
  SetServerURL,
  GetServerURL,
  CheckSoftEtherInstalled,
  GetSoftEtherVersion,
  EnsureSoftEtherRunning,
  GetPricing,
  GetShopInfo,
  PurchaseRoom,
  ExtendRoom,
  SetRoomRole,
  TransferRoom,
  GetMyStats,
  GetMe,
  CheckForUpdate,
  GetCurrentVersion,
  GetLocalVPNIP,
  SendChatMessage,
  GetChatMessages,
  CreateInvite,
  JoinByInvite,
  ChangePassword,
  RedeemPromo,
  GetReferralInfo,
  RefreshBalance,
} from "../wailsjs/go/main/App";

// Re-export everything so the rest of the frontend imports from one place.
export {
  Register,
  Login,
  GetDeviceFingerprint,
  ListRooms,
  GetRoom,
  JoinRoom,
  LeaveRoom,
  GetMembers,
  GetBuyInfo,
  ConnectVPN,
  DisconnectVPN,
  StopVPN,
  GetVPNStatus,
  PingServer,
  GetPingStats,
  GetConnectionQuality,
  CheckVPNReady,
  IsSplitTunnelActive,
  SetServerURL,
  GetServerURL,
  CheckSoftEtherInstalled,
  GetSoftEtherVersion,
  EnsureSoftEtherRunning,
  GetPricing,
  GetShopInfo,
  PurchaseRoom,
  ExtendRoom,
  SetRoomRole,
  TransferRoom,
  GetMyStats,
  GetMe,
  CheckForUpdate,
  GetCurrentVersion,
  GetLocalVPNIP,
  SendChatMessage,
  GetChatMessages,
  CreateInvite,
  JoinByInvite,
  ChangePassword,
  RedeemPromo,
  GetReferralInfo,
  RefreshBalance,
};
