// Placeholder for Wails runtime bindings.
// Auto-generated by Wails during build. These stubs prevent import errors.

export function EventsOn(eventName, callback) {}
export function EventsOff(eventName) {}
export function EventsEmit(eventName, data) {}
export function LogDebug(message) {}
export function LogInfo(message) {}
export function LogWarning(message) {}
export function LogError(message) {}
export function Quit() {}
